### ISSUE TITLE
[FEATURE] - Hide dev alpha/beta/rc version from suggestion

### ISSUE THREAD

**Issue by jonagoldman** [Gael-Lopes-Da-Silva/DependedVSCode#7]
**Description**

Currently, the latest version is suggested, even if its an dev/alpha/beta/rc version:

![Screenshot From 2024-12-13 13-26-22](https://github.com/user-attachments/assets/8b7f7bcd-56fd-4a22-a565-ef93a1a37a7f)

It will be nice to configure to show only stable versions.

**Comment by Gael-Lopes-Da-Silva** [comment]
With update 0.0.6, I added 4 options to only show latest stable version.
By default we show all versions available, if you want to only show stable versions for javascript, just switch the corresponding option to true.

If you change this options will there already exists a cache (you already opened a package.json or whatever supported) the change will not apply directly, you will need update the cache via the command palette or just reload the window.

```json
{
    "depended.javascript.stable": false, // Only show stable version when fetch latest version for javascript
    "depended.rust.stable": false, // Only show stable version when fetch latest version for rust
    "depended.php.stable": false, // Only show stable version when fetch latest version for php
    "depended.python.stable": false, // Only show stable version when fetch latest version for python
}
```

Right now we check for (alpha|beta|rc|dev|post|preview|snapshot|canary) so if you see any weird behavior, you can open a new issue (version naming is not standardized).
